### ISSUE TITLE
Performance running serverside

### ISSUE THREAD

**Issue by JustMeDaFaq** [nakardo/node-gameboy#2]
Hi,
dunno if im doing something wrong, tho, performance is bad when using it via nodejs. 
Probably around 30-40% of the original games speed.

Is it just because the emulator isnt finished yet or a technical limitation?

Thanks in advance ;)

**Comment by nakardo** [comment]
It's more a technical limitation. First, frames are being capped to 30fps
on this line:

https://github.com/nakardo/node-gameboy/blob/master/examples/ws/server.js#L18

By removing that line, you'll have peaks around 30-40fps (which makes
suffer gameplay). The reason is extra time is needed on the server for
converting each frame to PNG blobs and broadcast them through the sockets.

That's the major drawback of running server side. I've tried to make some
optimizations but couldn't get much improvement by the effort needed.

If you find out some improvement about it, feel free to submit a PR.

Il 07 apr 2017 2:45 PM, "JustMeDaFaq" <notifications@github.com> ha scritto:
